---
apiVersion: v1
kind: Namespace
metadata:
  name: news-crawler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-crawler
  namespace: alert-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: alert
    spec:
      hostAliases:
        - ip: "172.31.23.75"
          hostnames:
            - "mh-x1"
        - ip: "172.31.18.157"
          hostnames:
            - "mh-x5"
      containers:
        - name: news-crawler
          image: mhhub.alert.vn/service/news-crawler:v1.0
          env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi