# AUTOGENERATED BY THE GRADLE SCRIPT. EDITS WILL BE OVERWRITTEN.
# encoding: utf-8
require "logstash/filters/base"
require "logstash/namespace"
require "logstash-filter-news_post_filter_jars"
require "java"

class LogStash::Filters::NewsPostFilter < LogStash::Filters::Base
  config_name "news_post_filter"

  def self.javaClass() Java::org.logstashplugins.NewsPostFilter.java_class; end
end
